import { Geist_Mono, Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { AdminShell } from "@/app/components/AdminShell";
import { Navbar } from "@/app/components/Navbar";

const playfairDisplay = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
    weight: ["600", "700", "800"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children, }) {
    return (<html lang="en" className={`${playfairDisplay.variable} ${poppins.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-gradient-to-br from-rose-50 via-pink-50 to-purple-50">
        <Providers>
          <Navbar />
          <AdminShell>{children}</AdminShell>
        </Providers>
      </body>
    </html>);
}
